repos:
  # black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ["--config", "./pyproject.toml"]
    # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config", "./.flake8"]
    # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 0.6.8
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
