repos:
  # black
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--config", "./pyproject.toml"]
    # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--config", "./.flake8"]
    # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 0.6.8
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Zac-HD/shed
    rev: 2024.3.1
    hooks:
      - id: shed
        # args: [--refactor, --py311-plus]
        types_or: [python, pyi, markdown, rst]
