[project]
name = "zhukebot"
version = "0.1.0"
description = "烛客机器人"
authors = [
    {name = "dao_mingze", email = "dao_mingze@163.com"},
]
dependencies = [
    "nb-cli>=1.0.5",
    "nonebot-plugin-gocqhttp>=0.6.8",
    "nonebot-plugin-guild-patch>=0.2.3",
    "nonebot-plugin-status>=0.6.1",
    "nonebot-plugin-revoke>=0.1.0",
    "nonebot2>=2.0.0rc3",
    "beautifulsoup4>=4.11.2",
    "nonebot-plugin-apscheduler>=0.2.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = ["nonebot_plugin_gocqhttp", "nonebot_plugin_status", "nonebot_plugin_guild_patch", "nonebot_plugin_revoke", "nonebot_plugin_help", "nonebot_plugin_apscheduler", "nonebot_plugin_htmlrender", "nonebot_plugin_chatgpt"]
plugin_dirs = ["zhukebot/plugins"]
builtin_plugins = ["echo"]

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
